apiVersion: apps/v1
kind: Deployment 
metadata:
  name: dev-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
        app: snake
  template:
    metadata:
      labels:
        app: blinkit
    spec:
      containers:
        - name: snake-container
          image: venky223/snake-game
          ports:
            - containerPort: 80
